### ISSUE TITLE
Shifts are not shown in personal calendars of its attendees

### ISSUE THREAD

**Issue by weits** [csoc-de/Shifts#30]
When I create a shift and add an worker to it, I would like to not only create an event in shifts calendar but in attendees's personal calendars too. Is it somehow possible?

**Comment by fkirchesch** [comment]
Hey @weits,
do you mean that you want to create Shifts in de Nextcloud Kalendar App and it to be displayed in the shifts-app aswell ?
Or do you talk about the created Shifts in my app to be displayed in the attendees personal Nextcloud Calendar ?
If you mean the second, then this should already be implemented behind the Calendar Sync button.

Best regards

Fabian

**Comment by weits** [comment]
Hi, thanks for your answer. I ment the second option. I create shiftplan, then set some shifts to people. In the calendar, I see events for shifts with right names, and right attendees properly added. Every one of the attendees has their own personal calender, but the events are not there. I hope it is clear as my english is not very good ;-)

**Comment by weits** [comment]
Hi, is there any progress? What is very strange is that when I edit manually the calendar events created by Shiftplan and add/remove participants I still cannot see the event in the participants' personal calendars.

**Comment by LeaKaftan** [comment]
Hi weits, I have no affiliation what-so-ever with this project besides starting to use it, too, but I think what you might try out is sharing the calendar that is synchronized with the Shifts app with your attendees so that they have access to the calendar, too. As long as you do not share the calendar with them, they are not allowed to see the calendar entries. I think, thoug not sure here, that the calendar is not automatically synchronized with the personal ones, but just with the attached calendar.

**Comment by weits** [comment]
@LeaKaftan The shifts calendar is shared to shift administrators and shift attendees too. The problem is not that attendees does not see the common event in shifts calendar. They do not see events in their personal calendars.

**Comment by csoc-kevink** [comment]
Does this bug still exists with version v1.9.1?

**Comment by berveles** [comment]
After installing the app and assigning the right groups and users, I added a calendar in the app's settings. 
![image](https://github.com/csoc-de/Shifts/assets/76174355/2d3a1509-1772-40b3-b5a5-eed072720ef7)
![image](https://github.com/csoc-de/Shifts/assets/76174355/41634a1f-93e6-42be-b5aa-3dc87d9240c6)
This calendar was created manually by my user
However, when synchronizing the calendar using the corresponding button, an error occurs.
![image](https://github.com/csoc-de/Shifts/assets/76174355/4986d001-f208-47f2-8613-a67b720474b8)
There are no markings on the calendar itself.

(Thank you for updating the application to the new version of nextcloud)

**Comment by csoc-kevink** [comment]
@berveles The app identifies the calendar by the organizer and calendar name. The calendar need to be created by the organizer.
If shift users should be able to see this calendar, it needs to be shared with them.
When the option "Add calendar events to the shift users calendar" is active, every shift user must visit the calendar app at least one to create the calendar in the backend. Otherwise the shifts app will throw an error because it cannot find the user calendar.
