### ISSUE TITLE
No new release - It is a pity

### ISSUE THREAD

**Issue by florom** [csoc-de/Shifts#33]
Its really a pity that you did not further develop this app.
It had a lot of potential but I somehow understand your behavior 
in regard what happened in the gstc Calendar context.

Just wanna let you know.

**Comment by csoc-technik** [comment]
We will release a Version for Nextcloud 25: [https://github.com/csoc-de/Shifts/issues/32#issuecomment-1452059103](url)

**Comment by privatemaker** [comment]
If you need any help (code or funding for this) I would be happy to collaborate!

**Comment by privatemaker** [comment]
@csoc-technik If you need any help (code or funding for this) I would be happy to collaborate!

**Comment by csoc-kevink** [comment]
We've released version 1.9.0 just now.
Feel free to test it and report any bugs. You can also make a pull request with a fix as it might take a while until we can fix issues.

**Comment by florom** [comment]
Hi @csoc-kevink ,

In nextcloud no version 1.9.0 is listed.

Can you have a look at that.

**Comment by csoc-kevink** [comment]
Hi @florom,

sorry for that. We were unable to upload the app into the appstore because of an error from the appstore itself.
Unfortunately we had no time to reproduce the error and make a proper error report to nextcloud. We try to fix that.
For testing purposes it it possible to clone the app into the app directory and build it with npm or use the attached artifact.
