### ISSUE TITLE
Working on Nextcloud 26.0.x ?

### ISSUE THREAD

**Issue by SilverNavigator** [csoc-de/Shifts#35]
I just want to know…

Thanks for the advancement to Nextcloud 25, does it work on the current Nextcloud 26 or will there be a new version for it soon?
Will this also be integrated in the AppStore?

Thanks

**Comment by domhaas** [comment]
@csoc-technik any news on Nextcloud 25/26 support and pushing the current version on the appstore? thanks.

**Comment by sonaxpro** [comment]
@SilverNavigator https://github.com/csoc-de/Shifts/issues/37#issuecomment-1645533015 yes, you can 1.8.6 to install.

**Comment by csoc-kevink** [comment]
We've released a new version 1.9.0 for Nextcloud 25 and 26. However, this version is not yet fully compatible with Nextcloud version 27.
We currently are unable to upload the release to the appstore since we are getting a signature error. We will try to get the new version into the appstore as soon as we can.
